version: 0.2

phases:
  install:
    runtime-Version:
      dotnet: 7.0.102

  pre-build:
    on-failure: ABORT
    commands:
    - echo Running test...
    - dotnet restore

  build:
    on-failure: ABORT
    commands:
    - echo building up the application...
    - dotnet build

post_build:
    on-failure: ABORT
    commands:
    - echo Build completed.

artifacts:
  files:
  - '**/*'
  name: robb-AWS_REGION