version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 7.0.102

  pre_build:
    on-failure: ABORT
    commands:
    - echo running test...
    - dotnet restore

  build:
    on-failure: ABORT
    commands:
    - echo building up the application...
    - dotnet build

post_build:
    on-failure: ABORT
    commands:
    - echo Running tests...
    - dotnet test --no-build --verbosity normal
    - echo Build Completed...

artifacts:
  files:
  - '**/*'
  name: robb-AWS_REGION